### PR TITLE
Second iteration

### PR DESCRIPTION
**Pull request by nofelmahmood**
Here it is ! 
Hey also try out searching recipes from spotlight !

### CODE REVIEW

**Comment by zenangst** [comment]
Oh crap, this is gonna be a problem;

problem

**Comment by nofelmahmood** [comment]
I almost got this feedback from you to divide code in separate concerns and avoid godzilla amounts of code in one file :P :dancers:

**Comment by zenangst** [comment]
@nofelmahmood you are referencing some local files in the Xcode project which causes it to break.

screen shot 2015-10-28 at 11 23 15

**Comment by nofelmahmood** [comment]
Sorry I forgot to remove them !

**Comment by nofelmahmood** [comment]
@zenangst Yes, nice suggestion. Hey just that I have to say this that there are a lot of things that had potential to be fixed and improved. But, I had to stop somewhere because in software I think you are never done.
I highly appreciate these feedbacks btw !

**Pull request merged**
